pipeline:
  install:
    image: node
    commands:
      - yarn install
  print-affected:
    image: node
      - git status
      - npx nx print-affected --base=origin/${CI_COMMIT_BRANCH} 
  lint:
    image: node
    commands:
      - npx nx affected --base=origin/${CI_COMMIT_BRANCH} --target=lint
  test:
    image: node
    commands:
      - npx nx affected --base=origin/${CI_COMMIT_BRANCH} --target=test
  build:
    image: node
    commands:
      - npx nx affected --base=origin/${CI_COMMIT_BRANCH} --target=build
  deploy:
    image: node
    commands:
      - echo "deploying"
